// Auto-ported from the pre-migration i18n.js dictionary, trimmed to only
// the keys this page actually references.
export type Lang = "ko" | "en"

export const dict: Record<Lang, Record<string, string>> = {
  ko: {
    "beyond.name": "BeyondMoment",
    "beyondPage.desc": "BeyondMoment는 당신의 소중한 순간을 이더리움 블록체인에 영구히 기록하고, 하나의 별자리로 이어 보여주는 MoonIK의 두 번째 앱 구상입니다.",
    "beyondPage.title": "BeyondMoment — Every moment, beyond time. | MoonIK",
    "bmPage.card1Desc": "이더리움 블록체인에 새겨진 기록은 누구도 변경하거나 지울 수 없습니다. 서비스가 사라져도 당신의 순간은 남습니다.",
    "bmPage.card1Title": "영원히 기록되는 순간",
    "bmPage.card2Desc": "블록 번호와 타임스탬프로, 흩어져 있던 순간들이 하나의 선으로 자연스럽게 연결됩니다.",
    "bmPage.card2Title": "시간을 잇는 여정",
    "bmPage.card3Desc": "기록이 쌓일수록 별은 늘어나고, 세상에 단 하나뿐인 당신의 별자리가 완성됩니다.",
    "bmPage.card3Title": "당신만의 별자리",
    "bmPage.comic1": "우리는 매일, 소중한 순간을 만나요.",
    "bmPage.comic2": "하지만 사진도, 글도, 서버가 사라지면 함께 사라져요.",
    "bmPage.comic3": "그래서 사람이 먼저 확인한 순간만, 블록체인에 새겨요.",
    "bmPage.comic4": "누구도 지우거나 바꿀 수 없어요. 회사가 사라져도요.",
    "bmPage.comic5": "당신의 순간은, 시간이 흘러도 그 자리에 남아요.",
    "bmPage.comicCoverHint": "클릭해서 이야기를 펼쳐보세요",
    "bmPage.comicCoverTitle": "왜, 영원한 기록일까?",
    "bmPage.comicPanelPlaceholder": "이미지 자리",
    "bmPage.comicScrollHint": "SCROLL",
    "bmPage.cta1": "내 별자리 만들기",
    "bmPage.cta2": "앱 미리보기",
    "bmPage.emailPlaceholder": "이메일 주소",
    "bmPage.heroDesc": "당신의 소중한 순간을 이더리움 블록체인에 영구히 기록하고,<br />시간의 흐름 속에서 하나의 별자리로 아름답게 이어 보여줍니다.",
    "bmPage.inviteDesc": "사전 등록하시면 정식 출시 시 가장 먼저 초대해 드립니다.",
    "bmPage.inviteTitle": "오늘의 순간을<br />첫 번째 별로.",
    "bmPage.mockAuthorLabel": "Author",
    "bmPage.mockBlockLabel": "Ethereum Block",
    "bmPage.mockCal1": "We got married.",
    "bmPage.mockCal2": "Thank you for being with me.",
    "bmPage.mockCal3": "A peaceful morning.",
    "bmPage.mockConstellation": "My Constellation",
    "bmPage.mockEntry1": "Our story begins.",
    "bmPage.mockEntry2": "Luna came<br />into our lives.",
    "bmPage.mockEntry3": "Our first trip.",
    "bmPage.mockMarried": "We got<br />married.",
    "bmPage.mockMoment": "Moment",
    "bmPage.mockNavJourney": "Journey",
    "bmPage.mockNavMoments": "Moments",
    "bmPage.mockNavProfile": "Profile",
    "bmPage.mockNavSearch": "Search",
    "bmPage.mockTimestampLabel": "Timestamp",
    "bmPage.mockTxLabel": "Transaction",
    "bmPage.noSpam": "스팸은 보내지 않습니다.",
    "bmPage.phone1Caption": "전체 여정",
    "bmPage.phone1Sub": "당신의 모든 순간이 별자리로 이어집니다.",
    "bmPage.phone2Caption": "순간 상세 보기",
    "bmPage.phone2Sub": "하나의 별을 탭하면 그 순간이 열립니다.",
    "bmPage.phone3Caption": "월별 · 검색",
    "bmPage.phone3Sub": "시간의 흐름을 달력처럼 훑어볼 수 있어요.",
    "bmPage.registerBtn": "사전 등록",
    "bmPage.s1Desc": "기록은 남기는 순간부터 당신의 것이 아니라, 시간의 것이 됩니다.",
    "bmPage.s1Title": "사라지지 않는 세 가지 약속",
    "bmPage.s2Desc": "전체 여정을 한눈에, 하나의 순간을 깊이. 별을 탭하면 그날의 기록이 열립니다.",
    "bmPage.s2Title": "밤하늘을 넘기는 방식으로",
    "bmPage.s3Title": "네 걸음이면 영원해집니다",
    "bmPage.s4Desc": "기록이 계속될수록 당신의 별자리는 더 넓어지고 더 밝게 빛납니다.",
    "bmPage.s4Title": "무한히 이어지는 별자리",
    "bmPage.step1Desc": "오늘의 순간을 200자 안에 담아 짧은 글로 남깁니다.",
    "bmPage.step1Title": "작성하기",
    "bmPage.step2Desc": "한 번 기록되면 수정할 수 없으니, 마지막으로 확인합니다.",
    "bmPage.step2Title": "검토하기",
    "bmPage.step3Desc": "블록체인에 새겨집니다. 평균 12초, 그리고 영원.",
    "bmPage.step3Title": "기록하기",
    "bmPage.step4Desc": "새로운 별 하나가 당신의 별자리에 추가되었습니다.",
    "bmPage.step4Title": "완료",
    "footer.contact": "문의하기",
    "footer.home": "홈",
    "nav.about": "회사 소개",
    "nav.back": "← 메인으로",
    "nav.dallae": "달래",
  },
  en: {
    "beyond.name": "BeyondMoment",
    "beyondPage.desc": "BeyondMoment permanently records your precious moments on the Ethereum blockchain and connects them into one constellation over time. MoonIK's second app concept.",
    "beyondPage.title": "BeyondMoment — Every moment, beyond time. | MoonIK",
    "bmPage.card1Desc": "Nothing carved into the Ethereum blockchain can be changed or erased by anyone. Even if the service disappears, your moments remain.",
    "bmPage.card1Title": "Moments recorded forever",
    "bmPage.card2Desc": "Block numbers and timestamps naturally connect your scattered moments into a single line.",
    "bmPage.card2Title": "A journey through time",
    "bmPage.card3Desc": "The more you record, the more stars appear — completing a constellation that belongs only to you.",
    "bmPage.card3Title": "A constellation of your own",
    "bmPage.comic1": "Every day, we live a moment worth keeping.",
    "bmPage.comic2": "But photos and words vanish when the server does.",
    "bmPage.comic3": "So we engrave only human-verified moments onto the blockchain.",
    "bmPage.comic4": "No one can erase or change it — not even if the company disappears.",
    "bmPage.comic5": "Your moment stays there, no matter how much time passes.",
    "bmPage.comicCoverHint": "Click to open the story",
    "bmPage.comicCoverTitle": "Why does it last forever?",
    "bmPage.comicPanelPlaceholder": "Image goes here",
    "bmPage.comicScrollHint": "SCROLL",
    "bmPage.cta1": "Create my constellation",
    "bmPage.cta2": "Preview the app",
    "bmPage.emailPlaceholder": "Email address",
    "bmPage.heroDesc": "We permanently record your precious moments on the Ethereum blockchain,<br />and beautifully connect them into a constellation across time.",
    "bmPage.inviteDesc": "Pre-register and we'll be sure to invite you first when we launch.",
    "bmPage.inviteTitle": "Turn today's moment<br />into your first star.",
    "bmPage.mockAuthorLabel": "Author",
    "bmPage.mockBlockLabel": "Ethereum Block",
    "bmPage.mockCal1": "We got married.",
    "bmPage.mockCal2": "Thank you for being with me.",
    "bmPage.mockCal3": "A peaceful morning.",
    "bmPage.mockConstellation": "My Constellation",
    "bmPage.mockEntry1": "Our story begins.",
    "bmPage.mockEntry2": "Luna came<br />into our lives.",
    "bmPage.mockEntry3": "Our first trip.",
    "bmPage.mockMarried": "We got<br />married.",
    "bmPage.mockMoment": "Moment",
    "bmPage.mockNavJourney": "Journey",
    "bmPage.mockNavMoments": "Moments",
    "bmPage.mockNavProfile": "Profile",
    "bmPage.mockNavSearch": "Search",
    "bmPage.mockTimestampLabel": "Timestamp",
    "bmPage.mockTxLabel": "Transaction",
    "bmPage.noSpam": "We won't send spam.",
    "bmPage.phone1Caption": "The whole journey",
    "bmPage.phone1Sub": "Every moment of yours connects into a constellation.",
    "bmPage.phone2Caption": "See a moment in detail",
    "bmPage.phone2Sub": "Tap a single star and that moment opens up.",
    "bmPage.phone3Caption": "Monthly view · Search",
    "bmPage.phone3Sub": "Browse through time like flipping through a calendar.",
    "bmPage.registerBtn": "Pre-register",
    "bmPage.s1Desc": "The moment you record it, it belongs not to you, but to time itself.",
    "bmPage.s1Title": "Three promises that never fade",
    "bmPage.s2Desc": "See the whole journey at a glance, or go deep into a single moment. Tap a star to open that day's record.",
    "bmPage.s2Title": "Swipe through the night sky",
    "bmPage.s3Title": "Four steps to forever",
    "bmPage.s4Desc": "The more you record, the wider and brighter your constellation grows.",
    "bmPage.s4Title": "A constellation that grows forever",
    "bmPage.step1Desc": "Capture today's moment in a short note, up to 200 characters.",
    "bmPage.step1Title": "Write",
    "bmPage.step2Desc": "Once recorded, it can't be edited — so take one last look before you commit.",
    "bmPage.step2Title": "Review",
    "bmPage.step3Desc": "It's carved into the blockchain. About 12 seconds — then forever.",
    "bmPage.step3Title": "Record",
    "bmPage.step4Desc": "A new star has been added to your constellation.",
    "bmPage.step4Title": "Done",
    "footer.contact": "Contact",
    "footer.home": "Home",
    "nav.about": "About",
    "nav.back": "← Home",
    "nav.dallae": "Dallae",
  },
}
